# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: Z-Wave Alliance <https://z-wavealliance.org>
---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
